version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      POSTGRES_DB: postgres-zoomcamp
    ports:
      - "5432:5432"
    volumes:
      - "/workspaces/ZainDEZoomcamp2025/week_2_workflow_orchestration/postgres/postgres-data:/var/lib/postgresql/data:rw"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "80:80"
volumes:
  postgres-data: